---
- hosts: product 
  connection: local
  become: True

  tasks:
  - name: "Update Service Catalog Product"
    command: ./boto/update_product.py -p {{ productname }} -t {{ cfn_template }} -b {{ s3bucket }} -v {{ version }}
